### ISSUE TITLE
Ne fonctionne pas chez moi ...

### ISSUE THREAD

**Issue by benjamincorailfactory** [PayGreen/Examples#1]
Bonjour,

Je suis en HTTPS (mais sans certificat signé car en dev local)
J’exécute yarn encore dev-server pour faire tourner mon node.
Et ... ça ne fonctionne pas.

Aucun problème en utilisant l'API en PHP , en revanche

**Comment by MattMattC** [comment]
Bonjour @benjamincorailfactory 

`yarn encore dev-server` est une commande pour lancer une application Front. L'exemple présent ici https://github.com/PayGreen/Examples/blob/main/node-back-axios/README.md est un code JS à utiliser sur un Back End JS.

Si vous utilisez yarn encore, je suppose que vous avez un symfony en amont, c'est à lui d'effectuer la requête à l'api PayGreen.

**Comment by benjamincorailfactory** [comment]
Bonjour @MattMattC,

Merci pour votre réponse.
Oui, j'utilise habituellement une version hybride Symfony / node pour mes fichiers vuejs.
Je sais que yarn encore dev ne fait que compiler. Mais en mode dev-server ....
J'étais dans un environnement connu pour les tests. Je vais donc me me mettre sur du full node (symfony n'est pas suffisant pour mon projet).

Merci, ça m'a évité de perdre du temps
